### ISSUE TITLE
GitHub action中获取仓库星星数

### ISSUE THREAD

**Issue by alanhg** [alanhg/others-note#344]
```yml
# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Star Count
        run: |
          star=`curl -s 'https://api.github.com/repos/${{github.repository}}?page=$i&per_page=100' | jq .stargazers_count`
          echo "repoStars=$star" >> $GITHUB_ENV
      - name: Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Someone stars **${{env.REPO_NAME}}** repository, see here(https://github.com/${{github.repository}}).
            There are currently ${{env.repoStars}} :star:, come on!
          format: markdown
```
